### ISSUE TITLE
www.mixcloud.com broken

### ISSUE THREAD

**Issue by borisshvonder** [ytdl-org/youtube-dl#22821]
- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.10.22**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
$ youtube-dl --verbose 'https://www.mixcloud.com/nicolemoudaber/in-the-mood-episode-284/'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.mixcloud.com/nicolemoudaber/in-the-mood-episode-284/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.10.22
[debug] Python version 3.6.9 (CPython) - FreeBSD-12.0-RELEASE-p10-amd64-64bit-ELF
[debug] exe versions: ffmpeg 4.1.4, ffprobe 4.1.4
[debug] Proxy map: {}
[mixcloud] nicolemoudaber-in-the-mood-episode-284: Downloading webpage
ERROR: Unable to extract play info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/b/.local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/home/b/.local/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/home/b/.local/lib/python3.6/site-packages/youtube_dl/extractor/mixcloud.py", line 87, in _real_extract
    webpage, 'play info'), 'play info')
  File "/home/b/.local/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 1014, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/home/b/.local/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract play info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

## Description
Looks like site format changed again (?) and youtube-dl cannot download public tracks from mixcloud anymore. I searched for similar bugs (#22447, #22378) but they have different tracebacks and error messages.

**Comment by jchook** [comment]
Broken for me too, except I get a slightly different error:

```ExtractorError('Failed to extract matching stream info')```

```
➜ youtube-dl --verbose https://www.mixcloud.com/thefindmag/jenova-7-dusted-jazz-mix-incl-dday-one-bugseed-mononome-more/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.mixcloud.com/thefindmag/jenova-7-dusted-jazz-mix-incl-dday-one-bugseed-mononome-more/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.10.29
[debug] Python version 3.6.8 (CPython) - Linux-4.15.0-66-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.6, ffprobe 3.4.6, phantomjs 2.1.1
[debug] Proxy map: {}
[mixcloud] thefindmag-jenova-7-dusted-jazz-mix-incl-dday-one-bugseed-mononome-more: Downloading webpage
ERROR: Failed to extract matching stream info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/jchook/.local/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/home/jchook/.local/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/home/jchook/.local/lib/python3.6/site-packages/youtube_dl/extractor/mixcloud.py", line 96, in _real_extract
    raise ExtractorError('Failed to extract matching stream info')
youtube_dl.utils.ExtractorError: Failed to extract matching stream info; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by greentornado** [comment]
broken for me too.

**Comment by jchook** [comment]
@remitamine did you intend to close this issue?

I don't see the issue tracked in any open tickets now.

**Comment by remitamine** [comment]
because a fix has been pushed and will be available in the next version.

**Comment by jchook** [comment]
Awesome thank you @remitamine!

**Comment by trantrung22** [comment]
I have updated the latest version 2019.10.29 but still not fixed yet
