### ISSUE TITLE
ServusTV support is broken

### ISSUE THREAD

**Issue by puchu** [ytdl-org/youtube-dl#23475]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.11.28**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

ServusTV support is broken, URLs like
https://www.servustv.com/videos/aa-1y5h5gzas2112/
don't work anymore

**Comment by moviedino** [comment]
I'am adding the verbose log:

`youtube-dl -v https://www.servustv.com/videos/aa-1yk17cuc12112/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.servustv.com/videos/aa-1yk17cuc12112/']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2019.11.28
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg 4.2.1, ffprobe 4.2.1
[debug] Proxy map: {}
[generic] aa-1yk17cuc12112: Requesting header
WARNING: Falling back on generic information extractor.
[generic] aa-1yk17cuc12112: Downloading webpage
[generic] aa-1yk17cuc12112: Extracting information
ERROR: Unsupported URL: https://www.servustv.com/videos/aa-1yk17cuc12112/
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwy0zjfmc\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwy0zjfmc\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwy0zjfmc\build\youtube_dl\extractor\generic.py", line 3347, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.servustv.com/videos/aa-1yk17cuc12112/`

`youtube-dl -v https://www.servustv.com/videos/1393234154884-612144188/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.servustv.com/videos/1393234154884-612144188/']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2019.11.28
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg 4.2.1, ffprobe 4.2.1
[debug] Proxy map: {}
[generic] 1393234154884-612144188: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 1393234154884-612144188: Downloading webpage
[generic] 1393234154884-612144188: Extracting information
ERROR: Unsupported URL: https://www.servustv.com/videos/1393234154884-612144188/
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwy0zjfmc\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwy0zjfmc\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwy0zjfmc\build\youtube_dl\extractor\generic.py", line 3347, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.servustv.com/videos/1393234154884-612144188/`

`youtube-dl -v https://www.servustv.com/videos/aa-21vy5yw392112/
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.servustv.com/videos/aa-21vy5yw392112/']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2019.11.28
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg 4.2.1, ffprobe 4.2.1
[debug] Proxy map: {}
[generic] aa-21vy5yw392112: Requesting header
WARNING: Falling back on generic information extractor.
[generic] aa-21vy5yw392112: Downloading webpage
[generic] aa-21vy5yw392112: Extracting information
ERROR: Unsupported URL: https://www.servustv.com/videos/aa-21vy5yw392112/
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwy0zjfmc\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwy0zjfmc\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwy0zjfmc\build\youtube_dl\extractor\generic.py", line 3347, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.servustv.com/videos/aa-21vy5yw392112/`

**Comment by moviedino** [comment]
I checked the new update and unfortunately URL detection still does not work with 2019.12.25

**Comment by d4rk574lk3r** [comment]
Regexp is the problem...

@team
may somebody could change the Regexp in line 10 of Extractor servus.py
from:
`https?://(?:www\.)?servus\.com/(?:(?:at|de)/p/[^/]+|tv/videos)/(?P<id>[aA]{2}-\w+|\d+-\d+)`
to:
 `https?://(?:www\.)?servustv\.com/(?:(?:at|de)/p/[^/]+|videos)/(?P<id>[aA]{2}-\w+|\d+-\d+)`

**Comment by puchu** [comment]
the regex 

> Regexp is the problem...
> 
> @team
> may somebody could change the Regexp in line 10 of Extractor servus.py
> from:
> `https?://(?:www\.)?servus\.com/(?:(?:at|de)/p/[^/]+|tv/videos)/(?P<id>[aA]{2}-\w+|\d+-\d+)`
> to:
> `https?://(?:www\.)?servustv\.com/(?:(?:at|de)/p/[^/]+|videos)/(?P<id>[aA]{2}-\w+|\d+-\d+)`

the regex change works, thanks @d4rk574lk3r

**Comment by moviedino** [comment]
is it perhaps possible to integrate servus and servustv?
i have the strange feeling servus will someday change its URL back.

**Comment by puchu** [comment]
this should allow servus and servustv

```
diff --git a/youtube_dl/extractor/servus.py b/youtube_dl/extractor/servus.py
index e579d42..5e73058 100644
--- a/youtube_dl/extractor/servus.py
+++ b/youtube_dl/extractor/servus.py
@@ -7,7 +7,7 @@ from .common import InfoExtractor
 
 
 class ServusIE(InfoExtractor):
-    _VALID_URL = r'https?://(?:www\.)?servus\.com/(?:(?:at|de)/p/[^/]+|tv/videos)/(?P<id>[aA]{2}-\w+|\d+-\d+)'
+    _VALID_URL = r'https?://(?:www\.)?servus(tv)?\.com/(?:(?:at|de)/p/[^/]+|videos)/(?P<id>[aA]{2}-\w+|\d+-\d+)'
     _TESTS = [{
         'url': 'https://www.servus.com/de/p/Die-Gr%C3%BCnen-aus-Sicht-des-Volkes/AA-1T6VBU5PW1W12/',
         'md5': '3e1dd16775aa8d5cbef23628cfffc1f4',
```

**Comment by Oneboy1979** [comment]
> this should allow servus and servustv
> 
> ```
> diff --git a/youtube_dl/extractor/servus.py b/youtube_dl/extractor/servus.py
> index e579d42..5e73058 100644
> --- a/youtube_dl/extractor/servus.py
> +++ b/youtube_dl/extractor/servus.py
> @@ -7,7 +7,7 @@ from .common import InfoExtractor
>  
>  
>  class ServusIE(InfoExtractor):
> -    _VALID_URL = r'https?://(?:www\.)?servus\.com/(?:(?:at|de)/p/[^/]+|tv/videos)/(?P<id>[aA]{2}-\w+|\d+-\d+)'
> +    _VALID_URL = r'https?://(?:www\.)?servus(tv)?\.com/(?:(?:at|de)/p/[^/]+|videos)/(?P<id>[aA]{2}-\w+|\d+-\d+)'
>      _TESTS = [{
>          'url': 'https://www.servus.com/de/p/Die-Gr%C3%BCnen-aus-Sicht-des-Volkes/AA-1T6VBU5PW1W12/',
>          'md5': '3e1dd16775aa8d5cbef23628cfffc1f4',
> ```

I hope this is ok for you, i pushed your code!
[Pull request ](https://github.com/ytdl-org/youtube-dl/pull/23583)

**Comment by bluetiger300** [comment]
When is the above fix going to be integrated?
I have just updated to version 2020.01.15 and support is still broken.

youtube-dl https://www.servustv.com/videos/aa-1udr3r1w51w12/
[generic] aa-1udr3r1w51w12: Requesting header
WARNING: Falling back on generic information extractor.
[generic] aa-1udr3r1w51w12: Downloading webpage
[generic] aa-1udr3r1w51w12: Extracting information
ERROR: Unsupported URL: https://www.servustv.com/videos/aa-1udr3r1w51w12/

Thanks
