### ISSUE TITLE
URL Porn Link

### ISSUE THREAD

**Issue by gib7** [ytdl-org/youtube-dl#26511]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.07.28**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
PASTE VERBOSE LOG HERE
```
[liveuser@localhost-live ~]$ python youtube-dl -v "https://xhamster.com/videos/z44b-1941-ruff-ready-barefoot-fetishs-2791514"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://xhamster.com/videos/z44b-1941-ruff-ready-barefoot-fetishs-2791514']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.07.28
[debug] Python version 3.8.2 (CPython) - Linux-5.6.6-300.fc32.x86_64-x86_64-with-glibc2.2.5
[debug] exe versions: none
[debug] Proxy map: {}
[XHamster] 2791514: Downloading webpage
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "youtube-dl/youtube_dl/extractor/xhamster.py", line 242, in _real_extract
    self._sort_formats(formats)
  File "youtube-dl/youtube_dl/extractor/common.py", line 1350, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

## Description

WRITE DESCRIPTION HERE

youtube-dl breaks on xhamster.com causing the program to generate error messages handling the URL. xhamster.com domain requires an update to the youtube-dl project on github

**Comment by rtimai** [comment]
Add't info (same issue): Able to view video as live stream in browser.

$  sudo youtube-dl -U
[sudo] password for (user): 
youtube-dl is up-to-date (2020.07.28)
$  youtube-dl --verbose https://xhamster.com/videos/bucky-beaver-10-14742621
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://xhamster.com/videos/bucky-beaver-10-14742621']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.07.28
[debug] Python version 2.7.16 (CPython) - Linux-4.19.0-10-amd64-x86_64-with-debian-10.5
[debug] exe versions: ffmpeg 4.1.6-1, ffprobe 4.1.6-1, phantomjs ., rtmpdump 2.4
[debug] Proxy map: {}
[XHamster] 14742621: Downloading webpage
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/xhamster.py", line 242, in _real_extract
    self._sort_formats(formats)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1350, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

$

**Comment by PlaceboPRS** [comment]
If you're open to other solutions it downloads fine with Streamlink. I just got the URL using Video Download Helper in Waterfox: https://19-10.b.cdn13.com/hls/bsd/4000/sd/8000/002/791/514/240p.h264.mp4/index.m3u8?cdn_creation_time=1599116400&cdn_ttl=14400&cdn_cv_data=90.224.190.146&cdn_hash=3dc6f311d71f8e0826c2dbec4dd0c6f5

**Comment by nicolaasjan** [comment]
Maybe this is related to https://github.com/ytdl-org/youtube-dl/issues/26353 ?

Workaround mentioned there:
Change line 141 in`xhamster.py` to `r'window.initials\s*=\s*({.+?})\s*;<', webpage, 'initials',`

I applied that and then it works again:

```youtube-dl --verbose https://xhamster.com/videos/bucky-beaver-10-14742621
[debug] System config: []
[debug] User config: ['-o', '~/Desktop/%(title)s.%(ext)s', '-f', 'bestvideo[height<=1280][ext=mp4]+bestaudio[ext=m4a]/best', '--no-mtime']
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://xhamster.com/videos/bucky-beaver-10-14742621']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.07.28
[debug] Python version 3.6.9 (CPython) - Linux-4.15.0-115-generic-x86_64-with-LinuxMint-19.3-tricia
[debug] exe versions: ffmpeg N-98759-g1c7e55d, ffprobe N-98759-g1c7e55d
[debug] Proxy map: {}
[XHamster] 14742621: Downloading webpage
[debug] Invoking downloader on 'https://19-14.b.cdn13.com/014/742/621/240p.h264.mp4?cdn_creation_time=1599116400&cdn_ttl=14400&cdn_bw=78k&cdn_bw_fs=5218k&cdn_cv_data=217.121.193.63-dvp&cdn_hash=1b78a91c145668ee47ace3d53e47a0a1'
[download] Destination: /home/nico/Desktop/bucky beaver 10.mp4
[download]   3.5% of 264.48MiB at 185.74KiB/s ETA 23:26
............
```

**Comment by nicolaasjan** [comment]
> If you're open to other solutions it downloads fine with Streamlink. I just got the URL using Video Download Helper in Waterfox: https://19-10.b.cdn13.com/hls/bsd/4000/sd/8000/002/791/514/240p.h264.mp4/index.m3u8?cdn_creation_time=1599116400&cdn_ttl=14400&cdn_cv_data=90.224.190.146&cdn_hash=3dc6f311d71f8e0826c2dbec4dd0c6f5

<offtopic>
Your IP Adress is in that link ;) 
`&cdn_cv_data=*.*.*.*`

**Comment by PlaceboPRS** [comment]
> 
> Your IP Adress is in that link ;) `&cdn_cv_data=*.*.*.*`

Indeed, removed it from my post, would appreciate if you edit it out of your quote ;)

**Comment by rtimai** [comment]
Thanks all, for the responses. I have a problem, though. Youtube-dl is a binary file, which, even if I rename w/ ".zip" gets an Invalid Format error from Archive Manager (yes, as root sudo) -- so I can't edit the file. This is a copy that was installed using wget, not a regular apt-install, if it matters. Also, I'm on Chromium which doesn't support Video-Download-Helper. I bookmarked the issue #26353, and will study it some more when I can. Any suggestions will be appreciated. It may be a little while before I respond, but thanks.

**Comment by TheRealDude2** [comment]
I thought I was the only one who had the new problem with the initials. I have adapted the RegEx in my test version again. If the problem occurs with more than one, I will adjust it again and create a PR.

I assume that it will take some time until all outstanding patches are included in the xhamster.py extractor, again the hint that you can directly execute the latest code or your own customizations as described in the developer manual.

Download the repo as ZIP under code, unpack it. Then change to the directory and execute (as an example depending on the python version) "python3 -m youtube_dl https://xhamster.com/videos/bucky-beaver-10-14742621".

Before that, of course, something like the workaround should be added...

**Comment by rtimai** [comment]
@TheRealDude2 - Thanks so much for your response. I think I'll prefer to wait for the official update FOR NOW, but it's assuring to know that the issue has been recognized and a fix working its way down. Some time ago, someone posted a fix with instructions using the sed command to fix the Python version issue. If that's possible with this issue, that would be cool too. But, maybe not, considering some people are reporting the string to modify on different lines in xhamster.py.

**Comment by TheRealDude2** [comment]
I created a PR that should solve the problem. https://github.com/ytdl-org/youtube-dl/pull/26526

But I think the theme creator had the original problem, which was fixed with the last patch.

It would be good if those of you who use your own customized version of the xhamster.py extractor could test the line and give me feedback if problems occur.

I changed the line m with the regex for the initials to
r'window\.initials\s*=\s*({.+?})\s*;\s*</script>', webpage, 'initials',

This line should be in the line range 120-150 in xhamster.py, depending on the patch level you are using.

**Comment by nicolaasjan** [comment]
> It would be good if those of you who use your own customized version of the xhamster.py extractor could test the line and give me feedback if problems occur.
> 

Thanks!
No problems so far.

Were there any specific URL's, with which problems still occurred?

**Comment by TheRealDude2** [comment]
@nicolaasjan The problem is somewhat unspecific. It appeared in my case one day, then again not. Therefore I can't name a specific video. I'm just testing it again without the line adjustment, with a batch file to links. If the error occurs again, I send the URL.

Whatever. The PR is so far accepted. So in the next release version all bugs I know about the xhamster extractor are fixed.

**Comment by rtimai** [comment]
I just wanted you to know that I'm still watching, and sincerely appreciate
your efforts. --Roger

>

**Comment by TheRealDude2** [comment]
There is a new release version. 2020.09.06. I think there are ale problems with the xhamster.py fixed for the moment. Please update and try.

**Comment by rtimai** [comment]
Thanks so much, everyone, v.2020.09.06 seems to have restored function for me. The download is very slow, but probably because it's on a slow server. Retro nostalgia media that no one else is interested in. :-p --Rog
