### ISSUE TITLE
Unable to download ZOOM recorded videos. 

### ISSUE THREAD

**Issue by hope-lord** [ytdl-org/youtube-dl#30554]
## Checklist

- [ x] I'm reporting a broken site support issue
- [ x] I've verified that I'm running youtube-dl version **2021.12.17**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar bug reports including closed ones
- [ x] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://us06web.zoom.us/rec/share/5Qb3qHy_bi9WcGazy4W5j80PrQkOpbNIrgW-6vrRkRb5Q2xyxw7RWTJNG2KcO4J4.K-16KTWChtQT-R2h', '--video-password', 'PRIVATE', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.8.10 (CPython) - Linux-5.15.11-76051511-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, rtmpdump 2.4
[debug] Proxy map: {}
[zoom] 5Qb3qHy_bi9WcGazy4W5j80PrQkOpbNIrgW-6vrRkRb5Q2xyxw7RWTJNG2KcO4J4.K-16KTWChtQT-R2h: Downloading webpage
[zoom] 5Qb3qHy_bi9WcGazy4W5j80PrQkOpbNIrgW-6vrRkRb5Q2xyxw7RWTJNG2KcO4J4.K-16KTWChtQT-R2h: Validating passcode
ERROR: Wrong passcode: HTTP Error 401: Unauthorized (caused by <HTTPError 401: 'Unauthorized'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/extractor/common.py", line 634, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/lib/python3.8/dist-packages/youtube_dl/YoutubeDL.py", line 2288, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)

```

## Description

I am unable to download zoom recorded videos. It shows Unauthorized as well as  Wrong Passcode, though the passcode and links are correct.

**Comment by 89z** [comment]
Page requires Passcode. Please run the following command and comment back with the output:

~~~
echo PASSCODE | age -a -r age1zkz9g0kld97vs826j0r7p3ghvz3zcyd4tcqr2vrxpt0uux7mkycsl77hy6
~~~

https://github.com/FiloSottile/age

**Comment by hope-lord** [comment]
`-----BEGIN AGE ENCRYPTED FILE-----
YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPek0zOEJuUFVxdG4rWVZI
d0pUM3VBZmg2YjF0YllMZERMamtkZFBXYVVFCkFtWmVITGgxeWhPRlJzZ0RBZHBK
dlFhZjErb3RNdmJ2RDM1VWs5WUJRVjAKLS0tIFBycVVYeVgvSVgzOTlyVWV5ZDZm
MWlLRGZtdmEwRGNsdmVBc0owOERZTDQKScy96GINR1gYRDoIHr9ZXClMfxuZXitE
fdpKBKbz5221tzUogbiaNtM=
-----END AGE ENCRYPTED FILE-----
`

**Comment by hope-lord** [comment]
-----BEGIN AGE ENCRYPTED FILE-----
YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPek0zOEJuUFVxdG4rWVZI
d0pUM3VBZmg2YjF0YllMZERMamtkZFBXYVVFCkFtWmVITGgxeWhPRlJzZ0RBZHBK
dlFhZjErb3RNdmJ2RDM1VWs5WUJRVjAKLS0tIFBycVVYeVgvSVgzOTlyVWV5ZDZm
MWlLRGZtdmEwRGNsdmVBc0owOERZTDQKScy96GINR1gYRDoIHr9ZXClMfxuZXitE
fdpKBKbz5221tzUogbiaNtM=
-----END AGE ENCRYPTED FILE-----

**Comment by 89z** [comment]
You encrypted the literal string PASSCODE. The idea was that you would replace PASSCODE with the actual passcode...

**Comment by hope-lord** [comment]
-----BEGIN AGE ENCRYPTED FILE-----
YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3UlJMalExVXFDaHgycjdm
MCtpeC9PRkhkdEhJR0xBMEF4S3F6RmFFWm1zCk9oV1lOeE1USGE5elFVcU1hQWVD
Znp6aXhsd0hWSUc2N1lsN2JscWVmdncKLS0tIEtQTlZUY1hkWmVHV0ZQQ1I2S3JU
RnhZTWhMTHk5U1MvNTZtS0FodGFUQVkKWRK/SX8+zl6CQb6DmY4gJA45WgZg2slY
OVVbn+6lKUVqE+le8l51P1o=
-----END AGE ENCRYPTED FILE-----

**Comment by 89z** [comment]
Sorry I dont think I can help here. It seems you cant access those recordings at all from the Android client. I also tried from the Web client, and I found this request:

~~~
https://us06web.zoom.us/rec/validate_meet_passwd
~~~

which takes the passcode, but replaying the exact request fails randomly, and even when it does work, the tokens in the request expire after about 8 minutes, so pretty difficult to reverse that. Good luck to you.

**Comment by 89z** [comment]
If it helps, I found a workaround here:

https://github.com/lewisxy/zoom-recording-downloader#update-4162021

**Comment by hope-lord** [comment]
Thank you @89z. It helped a lot.

**Comment by Knight1** [comment]
You closed it but it was never fixed in youtube-dl :)

**Comment by bric3** [comment]
Agreed not fixed !
It may be a different issue, but now I have a 503

<details>

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-o', 'output-filename.mp4', '--referer', 'https://company.zoom.us', '--add-header', 'cookie: _zm_mtk_guid=edited; _zm_lang=en-US; notice_preferences=0:; notice_gdpr_prefs=0:; cmapi_gtm_bl=ga-ms-ua-ta-asp-bzi-sp-awct-cts-csm-img-flc-fls-mpm-mpr-m6d-tc-tdc; cmapi_cookie_privacy=permit 1 required; zm_oauth_cluster=aw1; _zm_csp_script_nonce=edited; zm_cluster=aw1; _zm_date_format=mm/dd/yy; notice_behavior=expressed,eu; _ga_L8TBF28DDX=GS1.1.1631180432.2.0.1631180440.0; _ga=GA1.2.1307786911.1630917755; _zm_launcher=1631880286237; _zm_login_acctype=7; OptanonAlertBoxClosed=2021-11-23T10:10:50.075Z; _zm_visitor_guid=edited; zm_zapps_action=EZWBMA; _zm_o2nd=edited; edited=edited; _zm_join_utid=edited; OnetrustActiveGroups=edited; edited; _zm_cid2=1;edited;edited;edited;edited; _zm_cid2_time="2022-09-10T07:40:38.011Z"; _zm_page_auth=aw1_c_edited; _zm_cdn_blocked=unlog_unblk; OptanonConsent=isGpcEnabled=1&datestamp=Sun+Sep+11+2022+19:55:13+GMT+0200+(Central+European+Summer+Time)&version=6.21.0&hosts=&groups=C0004:0,C0003:0,C0002:0,C0001:1&consentId=edited; _zm_fingerprint=edited; _zm_o2state=edited; zm_oauth_back_params=edited; _zm_ssid=aw1_c_edited; zm_aid=edited; zm_haid=697; _zm_currency=USD', 'https://ssrweb.zoom.us/replay02/2022/05/31/edited_Recording_1920x1080.mp4?response-content-type=video%2Fmp4&response-cache-control=max-age%3D0%2Cs-maxage%3D86400&edited']
[debug] Adding header from command line option cookie: _zm_mtk_guid=edited; _zm_lang=en-US; notice_preferences=0:; notice_gdpr_prefs=0:; cmapi_gtm_bl=ga-ms-ua-ta-asp-bzi-sp-awct-cts-csm-img-flc-fls-mpm-mpr-m6d-tc-tdc; cmapi_cookie_privacy=permit 1 required; zm_oauth_cluster=aw1; _zm_csp_script_nonce=edited; zm_cluster=aw1; _zm_date_format=mm/dd/yy; notice_behavior=expressed,eu; _ga_L8TBF28DDX=GS1.1.1631180432.2.0.1631180440.0; _ga=GA1.2.1307786911.1630917755; _zm_launcher=1631880286237; _zm_login_acctype=7; OptanonAlertBoxClosed=2021-11-23T10:10:50.075Z; _zm_visitor_guid=edited; zm_zapps_action=EZWBMA; _zm_o2nd=edited; edited=edited; _zm_join_utid=edited; OnetrustActiveGroups=edited; edited; _zm_cid2=1;edited;edited;edited;edited; _zm_cid2_time="2022-09-10T07:40:38.011Z"; _zm_page_auth=aw1_c_edited; _zm_cdn_blocked=unlog_unblk; OptanonConsent=isGpcEnabled=1&datestamp=Sun+Sep+11+2022+19:55:13+GMT+0200+(Central+European+Summer+Time)&version=6.21.0&hosts=&groups=C0004:0,C0003:0,C0002:0,C0001:1&consentId=edited; _zm_fingerprint=edited; _zm_o2state=edited; zm_oauth_back_params=edited; _zm_ssid=aw1_c_edited; zm_aid=edited; zm_haid=697; _zm_currency=USD
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.10.6 (CPython) - macOS-12.5.1-x86_64-i386-64bit
[debug] exe versions: rtmpdump 2.4
[debug] Proxy map: {}
[generic] edited_Recording_1920x1080.mp4?response-content-type=video/mp4&response-cache-control=max-age=0,s-maxage=86400&edited Requesting header
WARNING: Could not send HEAD request to https://ssrweb.zoom.us/replay02/2022/05/31/edited_Recording_1920x1080.mp4?response-content-type=video%2Fmp4&response-cache-control=max-age%3D0%2Cs-maxage%3D86400&edited: HTTP Error 503: Service Temporarily Unavailable
[generic] edited_Recording_1920x1080.mp4?response-content-type=video/mp4&response-cache-control=max-age=0,s-maxage=86400&edited: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 503: Service Temporarily Unavailable (caused by <HTTPError 503: 'Service Temporarily Unavailable'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 634, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 2288, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/local/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/local/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
```

</details>

The alternate method is using the browser directly.

> We found an alternative method to download zoom recordings using the browser's builtin video download functionality.
>
>   * Firefox: Hold SHIFT and right click the video, click on "Save Video As..." (no plugin needed).
>   * Chrome: Find a plugin that bypass right click restriction (for example, [this plugin](https://chrome.google.com/webstore/detail/allow-right-click/hompjdfbfmmmgflfjdlnkohcplmboaeo)), and then right click the video, click on "Save Video As..."

**Comment by RohanAdwankar** [comment]
These alternative methods no longer work, does anyone know of an up-to-date solution?
