### ISSUE TITLE
slow downloading 

### ISSUE THREAD

**Issue by KhaledAbdalmoaty2020** [ytdl-org/youtube-dl#30617]
## Checklist

- [ ] I'm reporting a broken site support issue
- [ ] I've verified that I'm running youtube-dl version **2021.12.17**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE
```

## Description

WRITE DESCRIPTION HERE

**Comment by dirkf** [comment]
If your problem is as in the issue title, you have [this problem](https://github.com/ytdl-org/youtube-dl/issues/30583#issuecomment-1027312830), fixed in git master. Or please open and complete an issue properly.

**Comment by mattia-lecci** [comment]
hi, since issue #30583 is locked, i'm writing here.
I installed youtube_dl using pip, and the issue is indeed still present.
Is there any plan to publish a new release? I see the last one is from december 2021, so many updates will probably be included.

Honestly, even just considering this fixed issue is definitely worth it for the community! Keep up the good work :)

**Comment by mattia-lecci** [comment]
thank you for the quick reply! I understand the process, I'm just wondering why such a relevant fix has not been pushed to a release yet

**Comment by dirkf** [comment]
Indeed: [definitive statement](https://github.com/ytdl-org/youtube-dl/issues/28859#issuecomment-1158188788).
