### ISSUE TITLE
Error when trying to download video from YT

### ISSUE THREAD

**Issue by dominikkociecki** [ytdl-org/youtube-dl#31719]
YT link: https://www.youtube.com/watch?v=oRdBWKKbU2s

ERROR MSG
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

![yt dl error](https://user-images.githubusercontent.com/38166176/221692701-9b375f61-155a-43d8-895b-16f5af3e88d2.jpg)

**Comment by Vangelis66** [comment]
... Check your bank account: You have been awarded $200 for opening the 200th duplicate issue of an existing one, with the exact same `ERROR` message 😜 ... 

Seriously though, start all-over-again by visiting PINNED issue #30839, read it in its entirety and perform all the required searches described therein; PLEASE, **don't create yet another duplicate**, please **close** this one...
**Hint**: When submitting issues, it's best to avoid screengrabs and post **text** (copied from your command prompt/PS window) instead... 😄

**Comment by dominikkociecki** [comment]
https://github.com/ytdl-org/youtube-dl/issues/30839

**Comment by dominikkociecki** [comment]
PS C:\Users\ZZZZ\Downloads> .\youtube-dl.exe https://www.youtube.com/watch?v=oRdBWKKbU2s --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/watch?v=oRdBWKKbU2s', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.22621
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] oRdBWKKbU2s: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\youtube.py", line 1794, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 1012, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by Vangelis66** [comment]
... If you haven't already 😉 , please go and read [this](https://github.com/ytdl-org/youtube-dl/issues/31530#issue-1587746229)... 

> There's no point posting your log that shows the error now: feel free to thumb-up [this post](https://github.com/ytdl-org/youtube-dl/issues/31530#issuecomment-1433230848)

**Comment by dominikkociecki** [comment]
> ... If you haven't already 😉 , please go and read [this](https://github.com/ytdl-org/youtube-dl/issues/31530#issue-1587746229)...
> 
> > There's no point posting your log that shows the error now: feel free to thumb-up [this post](https://github.com/ytdl-org/youtube-dl/issues/31530#issuecomment-1433230848)

There  is said that issue is fixed.
It's not.

**Comment by jacopomazzoni** [comment]
> > ... If you haven't already 😉 , please go and read [this](https://github.com/ytdl-org/youtube-dl/issues/31530#issue-1587746229)...
> > > There's no point posting your log that shows the error now: feel free to thumb-up [this post](https://github.com/ytdl-org/youtube-dl/issues/31530#issuecomment-1433230848)
> 
> There is said that issue is fixed. **It's not.**

a self applied patch that kinda works sometimes is not an acceptable solution. until they push it so it can be updated with a simple youtube-dl -U this isn't fixed.

**Comment by Vangelis66** [comment]
> this kind of attitude towards **your** users will only result in people abandoning the project for yt-dlp.

FTR, I'm not directly affiliated with the project, which is currently understaffed, with **only one active maintainer**, whose spare time is being consumed by editing/closing tens of duplicates people insist on submitting, without following the `Open a new issue` guidelines... 
Imagine stepping in his shoes for a while... It's nerve wrecking... 

The original issue **IS fixed** in source code (and in binary format, too), and if people had the "patience" to browse the linked issues, they would have found offered available solutions... 
Granted that for some cases, the solution isn't a one-liner... 
Most "users" want a quick fix, of course... Isn't that a form of entitlement? They have been using (for free) an open source software they've come to depend upon so much, yet when they're kindly ask to devote 5min of their time to explore what's currently available to remedy things, they object to that... 
... And inside the linked issues there is explanation why a "quick fix" has not yet been provided - but who cares to read? It's easier to press "New Issue"=> "Submit"...

BTW, being snarky is truly not a trait of me - guess I developed it after reading, for the past 5 days, ca. 160 dupes of the `ERROR: Unable to extract uploader id` issue... 
For those migrating to `yt-dlp`: on a future breakage of the same magnitude as that last one, their issue tracker (rightly) warns that: 

> - [ ] I understand that I will be blocked if I intentionally remove or skip any mandatory* field *
> ...
>- [ ] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates *
> - [ ] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue) *

... yet people continue in flocks to abuse this issue tracker here...

**Comment by dirkf** [comment]
Also: https://github.com/ytdl-org/youtube-dl/issues/31711#issuecomment-1446248519.
