### ISSUE TITLE
[YouTube] No video formats found

### ISSUE THREAD

**Issue by DonaldsoJo** [ytdl-org/youtube-dl#32533]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2023.08.28.40298**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
❯ .\youtube-dl -F https://youtu.be/Z5-rdr0qhWk?si=Hg_dbGgMSsDSSS7Y --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-F', 'https://youtu.be/Z5-rdr0qhWk?si=Hg_dbGgMSsDSSS7Y', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2023.08.28.40298 (single file build)
** This build is unofficial daily builds, provided for ease of use.
** Please do not ask for any support.
[debug] Python 3.4.4 (CPython AMD64 32bit) - Windows-10-10.0.19041 - OpenSSL 1.0.2d 9 Jul 2015
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] Z5-rdr0qhWk: Downloading webpage
[youtube] Z5-rdr0qhWk: Downloading API JSON
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: unable to extract player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "D:\a\youtube-dl\youtube-dl\youtube_dl\YoutubeDL.py", line 825, in wrapper
  File "D:\a\youtube-dl\youtube-dl\youtube_dl\YoutubeDL.py", line 846, in __extract_info
  File "D:\a\youtube-dl\youtube-dl\youtube_dl\extractor\common.py", line 535, in extract
  File "D:\a\youtube-dl\youtube-dl\youtube_dl\extractor\youtube.py", line 2121, in _real_extract
  File "D:\a\youtube-dl\youtube-dl\youtube_dl\extractor\common.py", line 1375, in _sort_formats
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Trying to download the audio of a YouTube video. (As I have for several years, using the same command format)
youtube-dl -f 140 https://youtu.be/Z5-rdr0qhWk?si=GQzP0TI3DqEMOc2U
I have the latest version. 
Other commands fail in the same way.
Summary trace:
   a long list of "WARNING: unable to extract player URL"
   followed by "ERROR: No video formats found"

**Comment by dirkf** [comment]
This seems to be another manifestation of #32499 and fixed by the WIP YT extractor that fixes that:
```console
$ python -m youtube_dl -v -F 'https://youtu.be/Z5-rdr0qhWk?si=GQzP0TI3DqEMOc2U'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-F', u'https://youtu.be/Z5-rdr0qhWk?si=GQzP0TI3DqEMOc2U']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: 86e3cf5e5
[debug] Python 2.7.15 (CPython i686 32bit) - Linux-6.1.0-11-686-pae-i686-with-debian-12.1 - OpenSSL 1.1.1a  20 Nov 2018 - glibc 2.1.3
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] Z5-rdr0qhWk: Downloading webpage
[youtube] Z5-rdr0qhWk: Downloading player c153b631
[debug] [youtube] Decrypted nsig VtPNynxZT9NIRusX => inur3uwD_Gn-KQ
[debug] [youtube] Decrypted nsig jrknynRP_TZIcnRl => CnkX3H-tkccp6w
[info] Available formats for Z5-rdr0qhWk:
format code  extension  resolution note
249          webm       audio only tiny   49k , webm_dash container, opus  (48000Hz), 1.32MiB
250          webm       audio only tiny   65k , webm_dash container, opus  (48000Hz), 1.75MiB
140          m4a        audio only tiny  127k , m4a_dash container, mp4a.40.2 (44100Hz), 3.38MiB
251          webm       audio only tiny  130k , webm_dash container, opus  (48000Hz), 3.46MiB
160          mp4        192x144    144p   11k , mp4_dash container, avc1.4d400c, 30fps, video only, 326.04KiB
278          webm       192x144    144p   24k , webm_dash container, vp9, 30fps, video only, 666.09KiB
394          mp4        192x144    144p   33k , mp4_dash container, av01.0.00M.08, 30fps, video only, 910.98KiB
133          mp4        320x240    240p   17k , mp4_dash container, avc1.4d400d, 30fps, video only, 482.46KiB
242          webm       320x240    240p   49k , webm_dash container, vp9, 30fps, video only, 1.31MiB
395          mp4        320x240    240p   67k , mp4_dash container, av01.0.00M.08, 30fps, video only, 1.80MiB
134          mp4        480x360    360p   37k , mp4_dash container, avc1.4d401e, 30fps, video only, 1008.61KiB
243          webm       480x360    360p   86k , webm_dash container, vp9, 30fps, video only, 2.30MiB
396          mp4        480x360    360p  111k , mp4_dash container, av01.0.01M.08, 30fps, video only, 2.95MiB
135          mp4        640x480    480p   89k , mp4_dash container, avc1.4d401e, 30fps, video only, 2.38MiB
244          webm       640x480    480p  137k , webm_dash container, vp9, 30fps, video only, 3.65MiB
397          mp4        640x480    480p  189k , mp4_dash container, av01.0.04M.08, 30fps, video only, 5.03MiB
18           mp4        480x360    360p  162k , avc1.42001E, 30fps, mp4a.40.2 (44100Hz) (best)
$
```

**Comment by Vangelis66** [comment]
@DonaldsoJo wrote: 

> I have the latest version.

... You think you are: 

```console
[debug] youtube-dl version 2023.08.28.40298 (single file build)
** This build is unofficial daily builds, provided for ease of use.
** Please do not ask for any support.
```
... but, in reality, you're NOT!

The "**unofficial daily builds**" that are being auto-released by **GitHub Actions** and are found in below repo: 

https://github.com/ytdl-patched/youtube-dl/tags

are, in fact, being compiled on **quite old** `yt-dl` source code, specifically `master-git-20230617-g07af479` from 2.5 months ago... 
As pinned issue #30839 explains (which you should've carefully read prior to filing a new issue here 😜 ), having the "latest" `yt-dl` version now implies you have migrated to the **"nightly" update channel**, 

https://github.com/ytdl-org/ytdl-nightly/releases/latest

which now is at version `2023.08.07` ; having done that, you'd have probably still encountered #32499 (as attested by @brickinthewall4138), but, at least, you'd have truly been on "latest" 😉 ...

@nicolaasjan wrote: 

> Same here. 

... Until **dirkf** kindly divulges the "WIP YT extractor" code 😄 , I "shoehorned" in `yt-dl`'s `youtube.py` the "downstream" fix from https://github.com/yt-dlp/yt-dlp/commit/378ae9f9fb8e8c86e6ac89c4c5b815b48ce93620
```console
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--ffmpeg-location', '.\\FFmpeg', '--external-downloader-args', '-v 8 -stats', '-vF', 'https://youtu.be/Z5-rdr0qhWk?si=GQzP0TI3DqEMOc2U']
[debug] Encodings: locale cp1253, fs mbcs, out cp737, pref cp1253
[debug] youtube-dl version 2023.08.04.2154
[debug] Lazy loading extractors enabled
[debug] Single file build
[debug] Python 3.4.10 (CPython x86 32bit) - Windows-Vista-6.0.6003-SP2 - OpenSSL 1.0.2k  26 Jan 2017
[debug] exe versions: ffmpeg n6.1-dev-1700-N-111584-ga4e6168, ffprobe n6.1-dev-1700-N-111584-ga4e6168, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] Z5-rdr0qhWk: Downloading webpage
[debug] [youtube] Decrypted nsig TFhF98o5a6EtYjbMd => KGICjS3bV6b6YA
[debug] [youtube] Decrypted nsig 0GmbWnEK-1sF-qZNI => tZ2cm3YsAW0_uQ
[info] Available formats for Z5-rdr0qhWk:
format code  extension  resolution note
249          webm       audio only tiny   49k , webm_dash container, opus  (48000Hz), 1.32MiB
250          webm       audio only tiny   65k , webm_dash container, opus  (48000Hz), 1.75MiB
140          m4a        audio only tiny  127k , m4a_dash container, mp4a.40.2 (44100Hz), 3.38MiB
251          webm       audio only tiny  130k , webm_dash container, opus  (48000Hz), 3.46MiB
160          mp4        192x144    144p   11k , mp4_dash container, avc1.4d400c, 30fps, video only, 326.04KiB
278          webm       192x144    144p   24k , webm_dash container, vp9, 30fps, video only, 666.09KiB
394          mp4        192x144    144p   33k , mp4_dash container, av01.0.00M.08, 30fps, video only, 910.98KiB
133          mp4        320x240    240p   17k , mp4_dash container, avc1.4d400d, 30fps, video only, 482.46KiB
242          webm       320x240    240p   49k , webm_dash container, vp9, 30fps, video only, 1.31MiB
395          mp4        320x240    240p   67k , mp4_dash container, av01.0.00M.08, 30fps, video only, 1.80MiB
134          mp4        480x360    360p   37k , mp4_dash container, avc1.4d401e, 30fps, video only, 1008.61KiB
243          webm       480x360    360p   86k , webm_dash container, vp9, 30fps, video only, 2.30MiB
396          mp4        480x360    360p  111k , mp4_dash container, av01.0.01M.08, 30fps, video only, 2.95MiB
135          mp4        640x480    480p   89k , mp4_dash container, avc1.4d401e, 30fps, video only, 2.38MiB
244          webm       640x480    480p  137k , webm_dash container, vp9, 30fps, video only, 3.65MiB
397          mp4        640x480    480p  189k , mp4_dash container, av01.0.04M.08, 30fps, video only, 5.03MiB
18           mp4        480x360    360p  162k , avc1.42001E, 30fps, mp4a.40.2 (44100Hz) (best)
```

**Comment by DonaldsoJo** [comment]
@Vangelis66 thanks for the clarification. 
I admit, I just used the -U option and assumed I had the "latest". Mea culpa.
But, as you expected, the nightly build didn't actually fix the problem. :-(

**Comment by dirkf** [comment]
Absent divulging, cookies should work round the issue per #32499.

**Comment by nicolaasjan** [comment]
> ... Until **dirkf** kindly divulges the "WIP YT extractor" code 😄 , I "shoehorned" in `yt-dl`'s `youtube.py` the "downstream" fix from [yt-dlp/yt-dlp@378ae9f](https://github.com/yt-dlp/yt-dlp/commit/378ae9f9fb8e8c86e6ac89c4c5b815b48ce93620)

Thanks for this!🌻

I applied the change in `youtube.py` and compiled again.
No error now. 🙂

**Comment by DonaldsoJo** [comment]
I tried the --cookies switch as described in the FAQ (search for cookies).
**This did indeed fix the problem**. So many thanks for the suggestion.

I was using Chrome and got the "get cookies.txt LOCALLY" extension.
I opened YouTube and the video I wanted.
Then created a cookies.txt file using the extension.
Then the following command line (and result):

>    youtube-dl --cookies .\www.youtube.com_cookies.txt -f 140 https://youtu.be/Z5-rdr0qhWk?si=-N0irE61t6FmzdSe
> [youtube] Z5-rdr0qhWk: Downloading webpage
> [dashsegments] Total fragments: 1
> [download] Destination: @TheCarsOfficial ― JUST WHAT I NEEDED (1978)-Z5-rdr0qhWk.m4a
> [download] 100% of 3.38MiB in 00:00
> WARNING: Z5-rdr0qhWk: writing DASH m4a. Only some players support this container. Install ffmpeg or avconv to fix this automatically.
> 

I'm ok with that kind of workaround, but it would be nice if youtube-dl worked without faffing with cookies.

Thanks for the help.
Should I close this issue? Or leave it open?
